### ISSUE TITLE
Validate Digits credential

### ISSUE THREAD

**Issue by arytbk** [felix-dumit/PFUser-Digits#1]
Thanks for this nice tool!
It looks like there is currently no validation when creating/authenticating a user from a DigitsID.
Maybe you could add support for this:
https://dev.twitter.com/twitter-kit/ios/oauth-echo
This way the Parse user would be created or logged-in only if the digits tokens get properly confirmed from the Cloud code by:
https://dev.twitter.com/rest/reference/get/account/verify_credentials

**Comment by felix-dumit** [comment]
It seems there is no config object for the digits instance to replace `[Twitter sharedInstance].authConfig` here:

```
TWTROAuthSigning *oauthSigning =
            [[TWTROAuthSigning alloc]
            initWithAuthConfig:
                [Twitter sharedInstance].authConfig
                authSession:session];
```

And not all apps using digits will want to use twitter login as well.

Let me know of any alternatives.

**Comment by arytbk** [comment]
The whole thing is described at the end of this thread:
https://twittercommunity.com/t/digits-how-can-i-verify-dgtsession-tokens-on-my-own-server/26036/16

it seems that the new Digits oAuthEcho method will provide the required tokens to send to a server so that this server can validate the Digits credentials. All this without requiring Twitter login.

So it looks like a perfect addition to PFUsers-Digits...

I must say that I am not proficient enough in Web dev to fully understand all the oAuth dance going on here :-) I hope you'll make sense of it!

**Comment by felix-dumit** [comment]
It was simpler than I thought, I pushed the change at: c3a7051c969c12a6e23e0d6ffead994b880f8598
