### ISSUE TITLE
Is there a way to set the parse username? or do we rely on "email" as the username?

### ISSUE THREAD

**Issue by ericlewis** [felix-dumit/PFUser-Digits#10]

**Comment by felix-dumit** [comment]
Previously the username was locked to the digitsId, but I just made a quick change so now:
If no username is set it will be set to your digitsId, but you are free to change the parse username anytime.

``` objc
[PFUser currentUser].username = @"ericlewis"
```

**Comment by ericlewis** [comment]
will that mess with login?

**Comment by felix-dumit** [comment]
It will just change the username, if your users can login via username as well as digits, then they can use the username you set.

**Comment by ericlewis** [comment]
cool. :) thanks so much.

**Comment by ericlewis** [comment]
and the user name is persisted, correct?

**Comment by felix-dumit** [comment]
Yes, as long as you save the user `[[PFUser currentUser] saveInBackground];`

**Comment by ericlewis** [comment]
sweet. thank you.
