### ISSUE TITLE
Verify the X-Auth-Service-Provider header, by parsing the uri and asserting the domain is api.digits.com, to ensure you are calling Digits.

### ISSUE THREAD

**Issue by alist** [felix-dumit/PFUser-Digits#11]
As I understand, this check is missing from `user.js:2` `verifyDigitsLogin`

Please see
https://docs.fabric.io/ios/digits/oauth-echo.html#obtaining-oauth-echo-headers

**Comment by felix-dumit** [comment]
This is actually exactly what is done in verifyDigitsLogin, the `requestUrl` and `authHeaders` are obtained client side (iOS) as described in that link and then sent over to parse for verification.

**Comment by brianjd** [comment]
@felix-dumit - he is referring to this from the bullet points at the bottom of the page:
- _Verify the X-Auth-Service-Provider header, by parsing the uri and asserting the domain is api.digits.com, to ensure you are calling Digits._

It's a quick addition, can probably send a PR later today or tomorrow.

**Comment by felix-dumit** [comment]
@brianjd Yes that's true I just looked at the link quickly.. If you could do it would be great, thanks!

**Comment by alist** [comment]
Thanks!
