### ISSUE TITLE
PFUser never logs out and Can't bring back Digits Signup Flow

### ISSUE THREAD

**Issue by otymartin** [felix-dumit/PFUser-Digits#13]
Two issues:
After initially signing up my PFUser, I can never get them to logout with any logout method.
Even after deleting the sessions and user in the Parse dashboard, the user still persists somewhere - magic. I occasionally get "Invalid session Token" errors.

That brings another issue:
I can't seem to bring back the Digits signup flow after initially creating a user on any given device.
The first time I try to signup -> I get the digitsSignup Flow.
## Once I logout and try again, that Flow no longer shows up. Instead I'm automatically logged in. No matter what I do, that Digits Flow is lost for good for some reason.

class LoginSignupViewController: UIViewController {
 override func viewDidLoad() {
        super.viewDidLoad()

```
    //If there is a user currently logged in, send them to the InitialViewController
    if PFUser.currentUser() != nil {
        dispatch_async(dispatch_get_main_queue()) {
        self.performSegueWithIdentifier("ShowInitialVC", sender: self)
        }
    }
}
```

}

//Digits login method
    @IBAction func loginSignupButton(sender: AnyObject) {

```
    PFUser.loginWithDigitsInBackground { (user:PFUser?, error:NSError?) -> Void in
        if error == nil {

            dispatch_async(dispatch_get_main_queue()) {
                self.performSegueWithIdentifier("ShowInitialVC", sender: self)
            }

        } else {
            print("there was an error")
        }
    }
}
```

//MY LOGOUT METHOD
class InitialViewController: UIViewController {

```
@IBAction func logoutButton(sender: AnyObject) {

    PFUser.logOutInBackground()

     //Go back to root view controller
    let mainStoryboard = UIStoryboard(name: "Main", bundle: nil)
    let loginSignupViewController = mainStoryboard.instantiateViewControllerWithIdentifier("LoginSignupViewController")
    presentViewController(loginSignupViewController, animated: true, completion: nil)
}
```

//PFUser+Digits.swift extension goes here!

**Comment by otymartin** [comment]
//My Storyboard
<img width="742" alt="screen shot 2015-12-16 at 11 41 28 pm" src="https://cloud.githubusercontent.com/assets/2222881/11861494/e78dff92-a44e-11e5-8f22-8ebc018f522a.png">

**Comment by otymartin** [comment]
arjun [12:02 AM] 
Hi Martin,

​[12:03] 
I’m just curious if the PFUser log out problem was solved?

Martin Otyeka [12:04 AM] 
hi no

​[12:04] 
did you see this on GitHub?

arjun [12:04 AM] 
I see that you have raised an issue on GitHub :simple_smile:

Martin Otyeka [12:04 AM] 
wow how are u able to tell?

arjun [12:05 AM] 
I wanted to use the extension  for swift, but saw couple of issues. Hence, I’m still wondering whether to use it or not.

Martin Otyeka [12:05 AM] 
The issue is probably on my end.

arjun [12:06 AM] 
Well, I saw that on GitHub and was curious if someone was using Parse with Digits.

Martin Otyeka [12:06 AM] 
The extension itself works and authenticates a user no prob

arjun [12:06 AM] 
on this slack channel

​[12:06] 
I see, may I know how you came to that conclusion?

Martin Otyeka [12:06 AM] 
i have it working

arjun [12:07 AM] 
aha I see, that’s good news!

​[12:07] 
so we can logout the user the usual way?

​[12:08] 
`PFUser.logOutInBackground()`

Martin Otyeka [12:08 AM] 
yes - but the issue is the session associated with the user still persists. I goggled the issue and everyone in some way has a problem logging out PFUser’s because the session and user still persists in the air or cloud somewhere

​[12:09] 
so my issue is, `PFUser.currentUser` is never `nil`. I tested and sometimes even if it is nil,  it doesnt bring up the DigitsSignup flow, it just automatically logs in when I click my login button which is wierd

arjun [12:11 AM] 
thats weird, I faced similar prb while using Digits itself. I tried this `Digits.sharedInstance().logOut()` and it worked

Martin Otyeka [12:12 AM] 
i think thats without Parse right??

arjun [12:12 AM] 
yup!

Martin Otyeka [12:12 AM] 
yea,

​[12:12] 
whoever wrote the extension im confident will have an answer tmorrow

​[12:13] 
i asked him over the weekend to translate the extension from ObjectiveC to swift and he did it the next day which was cool

arjun [12:13 AM] 
Wow, that’s awesome. Looks like a passionate guy.

​[12:14] 
I hope he will answer the query

​[12:14] 
But as of now, you are logging out the user the usual `PFUser` way right?

Martin Otyeka [12:14 AM] 
yes

arjun [12:15 AM] 
Cool. Thanks so much for the info. Cheers!

Martin Otyeka [12:15 AM] 
wait dude

​[12:15] 
u might have just helped me

arjun [12:16 AM] 
wow :joy:

Martin Otyeka [12:16 AM] 
YES INDEED U DID

​[12:16] 
haha

arjun [12:16 AM] 
thats awesome how?

​[12:16] 
LOL

Martin Otyeka [12:16 AM] 
``` @IBAction func logoutButton(sender: AnyObject) {
        
        PFUser.logOutInBackground()
        Digits.sharedInstance().logOut()
        
        let mainStoryboard = UIStoryboard(name: "Main", bundle: nil)
        let loginSignupViewController = mainStoryboard.instantiateViewControllerWithIdentifier("LoginSignupViewController")
        presentViewController(loginSignupViewController, animated: true, completion: nil)
        
        
    }```
(edited)

​[12:17] 
just added the `Digits.sharedInstance.logOut()` and all my problems are solved!!

arjun [12:17 AM] 
that’s crazy! maybe even Digits API needs to be notified about the log out session

Martin Otyeka [12:18 AM] 
yea i had no idea. i thought it would be handled in the extension or cloudcode cause god knows i don’t know whats written in it. i just use the method and ask no questions

arjun [12:18 AM] 
LOL

​[12:18] 
Luck just kicked your front door today.

​[12:19] 
Awesome man!

Martin Otyeka [12:21 AM] 
I know Im so amped. got my brother to signup to test and his ignorance has no respect for my minor achievements

​[12:21] 
Thank you so much dude!!

​[12:21] 
:raised_hands: how can i help you though? whats your trouble?

arjun [12:24 AM] 
I’ll BRB

Martin Otyeka [12:27 AM] 
cool

**Comment by otymartin** [comment]
Fixed.
@itsArjunn (twitter) hit me up on slack ios-developers group and sent me this `Digits.sharedInstance.logOut()` method which I added right underneath my `PFUser.logOut()` method.
All my problems disappeared.

I think what was happening was although `PFUser.logOut()` ended the PFUser session associated with `PFUser.currentUser`, a session still persisted with the DigitsAPI which you have to explicitly end.

Hence `Digits.sharedInstance.logOut()` 

I'm new to programming so I hope I framed the problem and solution correctly. Someone please check me on that if I'm wrong.

Also, if there is another solution, please feel free to share!

Thanks

**Comment by felix-dumit** [comment]
Hi Martin,

Yes the `Digits.sharedInstance.logOut()` is exactly what was needed. If you don't call it Digits will stay logged in even if Parse is logged out, so the next time it would log in instantly.

There no easy way to include that in this library without doing some really hackish stuff so it's best for each user of the library to implement that in each appropriate place. I'll add a note to the readme though to make that more clear.

**Comment by itsaark** [comment]
@felix-dumit Thanks so much for doing this. I have a question for you. How do I check whether the user who is signing in has an account created already on parse? I'm looking for something like `isNew` property in the code below. 

``` swift
PFFacebookUtils.logInInBackgroundWithReadPermissions(permissions) {
  (user: PFUser?, error: NSError?) -> Void in
  if let user = user {
    if user.isNew {
      print("User signed up and logged in through Facebook!")
    } else {
      print("User logged in through Facebook!")
    }
  } else {
    print("Uh oh. The user cancelled the Facebook login.")
  }
}
```

**Comment by felix-dumit** [comment]
@itsarjun Well after you login with digits every user will have an account (it will be created if it didn't exist before).
I never tested this but I think the `isNew` property would always be false since after login the user will have already been created, and saved, to Parse

**Comment by itsaark** [comment]
@felix-dumit I don't think so. `isNew` property works very well when parse is used with FB/Twitter sign in. The above code block is from Parse docs. When are user sign's in the `isNew` property checks if the instance(of the user) has just been created or sometime in the past. It returns `true` if the user has been added else `false` if the user already existed.
