### ISSUE TITLE
PFSession not created (?) upon successful login

### ISSUE THREAD

**Issue by laventura** [felix-dumit/PFUser-Digits#14]
Thanks for the _PFUser+Digits_ framework. Works good so far. 

I see one issue (maybe two).  Upon a successful sign-in with Phone number, I get a valid response in _PFUser.currentUser()_, which is great (and expected).
However, there is no associated _PFSession_ object. If I try to obtain _PFSession.getCurrentSession()_ it always returns an error (_Error Domain=Parse Code=209 "invalid session token"_).

Similarly, when I check the Parse data,  I see the User created correctly (I have two users, each corresponding to different phone numbers), but no objects in Session. 

Any idea what's contributing to this?

Thanks

**Comment by felix-dumit** [comment]
I just did a quick session here and I'm able to retrieve the session after login:

``` objc
[[[PFUser loginWithDigitsInBackground] continueWithSuccessBlock:^id(BFTask* task) {
    return [PFSession currentSession] getCurrentSessionInBackground];
}] continueWithBlock:^id(BFTask* task) {
    NSLog(@"Got session: %@ with error: %@", task.result, task.error);
}];
```

I think something you are doing after login is invalidating the session. Can you try calling any other parse method after login, like doing a query? It is likely they won't work because of the `invalid session token` error

**Comment by laventura** [comment]
Thanks for your quick reply!

I did essentially what you are doing

``` swift
       print("... Trying Parse Login with Digits in background")
        PFUser.loginWithDigitsInBackground().continueWithSuccessBlock { (task) -> AnyObject? in
            print(".... successful login")
            let user = PFUser.currentUser()
            let objId = user!.objectId!
            let phone = user!["phone"] as! String
            let stoken   = user!.sessionToken!
            print("PF User: \(objId), phone: \(phone), sess: \(stoken)")
            return PFSession.getCurrentSessionInBackground()
        }.continueWithBlock { (bftask) -> AnyObject? in
            let r = bftask.result as? String
            let e = bftask.error! as NSError
            print("Result: \(r), Error: \(e)")

            return nil
        }
```

And the successBlock is working ok: (I see valid values for objId, phone and even the sessionToken). The below returned token  `ABCDEFGHIJKLMXXXXXX` is what is returned by the Cloud Code function `loginWithDigits` so that works, I've verified.

```
.... successful login
PF User: lgg6BYmAe2, phone: +1123456789, sess: ABCDEFGHIJKLMXXXXXX
Result: nil, Error: Error Domain=Parse Code=209 "invalid session token" UserInfo={code=209, temporary=0, error=invalid session token, NSLocalizedDescription=invalid session token}
```

However, I _still_ get the _invalid session token, code=209_ error. Of course, the PFSession object is not created in Parse data store. 

I'm stumped. :(

**Comment by laventura** [comment]
BTW, I should mention the following settings on the Parse project:
Require Revocable Sessions ---> Set to NO (default was YES)
Revoke existing session tokens when user changes password --> set to NO (default was YES)

I don;t know if this helps.

**Comment by felix-dumit** [comment]
I think that's it then, when you don't have require revocable sessions enabled it doesn't create the PFSessions as each user only has one session (which is why the sessionToken is still printed). 

I didn't know that the `PFSession.currentSession()` was not available though. Why do you need it?

**Comment by laventura** [comment]
Ok thanks - that helped!  

So, just to clarify, I now set the Require Revocable Session to YES (the default) and also the Revoke Existing Session Tokens When User Changes Password to YET (also the default). 
Are these the recommended settings? 

[FYI : I _had_ set them to NO because I read elsewhere (the README?) that said to set them to NO. ]

Thx!

**Comment by felix-dumit** [comment]
```
if Revocable sessions = YES {
    Revoke Existing Session Tokens When User Changes Password = NO  
}
```

From README:

> If you are using revokable sessions, make sure to disable revoking sessions when user changes password

**Comment by laventura** [comment]
Thanks! that code is helpful 😀
I obviously misunderstood the original Readme. 
Many thx for your help.

My main aim is to try to use the `Digits.authenticateWithNavigationViewController`  (as I want to customize the theme ) along with the Parse+Digits. Will see how it goes.

**Comment by felix-dumit** [comment]
If you just want to customise the color and logo you can use like this [https://github.com/felix-dumit/PFUser-Digits#customising]
