### ISSUE TITLE
Function not found error 

### ISSUE THREAD

**Issue by kushal2905** [felix-dumit/PFUser-Digits#15]
Hi,

When i am using this class for login with digits  , i am getting this error "[Error]: function not found (Code: 141, Version: 1.9.1)".

this is my code : -
- (void)signInWithDigits
  {
  [[Digits sharedInstance] logOut];
  
  DGTAppearance *appearance = [DGTAppearance new];
  appearance.backgroundColor = [UIColor whiteColor];
  appearance.accentColor = [UIColor purpleColor];
  
  DGTAuthenticationConfiguration *configuration = [[DGTAuthenticationConfiguration alloc] initWithAccountFields:DGTAccountFieldsNone];
  configuration.appearance = appearance;
  configuration.title = @"Login with Digits";
  
  PFUser *oldUser = [PFUser currentUser];
  
  [PFUser loginWithDigitsInBackgroundWithConfiguration:configuration completion:^(PFUser *user, NSError *error) {}

can you please tell me what did i wrong ?

**Comment by felix-dumit** [comment]
Did you add the `user.js` file to CloudCode?

**Comment by kushal2905** [comment]
Oh i forgot this part. Let me upload it.
Thanks.
