### ISSUE TITLE
Add extra field to signup flow

### ISSUE THREAD

**Issue by otymartin** [felix-dumit/PFUser-Digits#16]
Hi,

I want to add a final step after signup asking a user for their "name" 

How could I do it?

This is my entire loginSignupCode

@IBAction func loginSignupButton(sender: AnyObject) {

```
    PFUser.loginWithDigitsInBackground { (user:PFUser?, error:NSError?) -> Void in
        if error == nil {

            dispatch_async(dispatch_get_main_queue()) {
                self.performSegueWithIdentifier("ShowMessagesViewController", sender: self)
            }


        } else {
            print("there was an error")
        }
    }
}
```

**Comment by felix-dumit** [comment]
There is no way to add that directly in the digits flow, so just like you're presenting the "ShowMessagesViewController" after login you'd have to present another view controller asking for the name (and that one will present ShowMessagesVC).
You can also ask for the name before showing the digits sign-in flow if that makes more sense in your app.

Btw - You don't need the dispatch in main queue in your code above as the completion already executes in the main thread.

**Comment by otymartin** [comment]
That for the fast response felix.

Ideally the logic I wanted to go with was after successful login/signup, check if user has a name set in the "name" column of the User class so I can present an UIAlertView asking for a name but I don't think Parse has a Query method to check if a given field is empty so I can't implement that logic. I attempted multiple ways that just ended in errors.

As for the dispatch, I was actually get an error before for some reason but I removed it this time and it works so thats for that :)

**Comment by felix-dumit** [comment]
You don't need to query, just check if `user.name == nil` then present the alert view.

EDIT: I usually subclass PFUser into my own class so I can specify the extra properties (like name), but if you don't the check would have to be: `user['name'] == nil`

**Comment by otymartin** [comment]
really, no background query needed? Will try this and check. Thanks felix

Update\* IT WORKS!!

You're the man!

**Comment by felix-dumit** [comment]
Yeah you already have the user object you just need to check its properties

Thanks,

Felix
