### ISSUE TITLE
Permanently Logged-in Users

### ISSUE THREAD

**Issue by otymartin** [felix-dumit/PFUser-Digits#17]
I want to have permanently logged in users just like whatsapp.

The only logic I have to implement this is to not have a logout method.

Is that sufficient or is there more to it than that?

I'm not familiar with Digits sessions - How long they persist along with parse.

**Comment by felix-dumit** [comment]
Yeah as long as you don't logout it will keep logged in.

**Comment by otymartin** [comment]
Thanks
