### ISSUE TITLE
Parse shutting down - What now

### ISSUE THREAD

**Issue by otymartin** [felix-dumit/PFUser-Digits#18]
Im sure you heard the depressing news that Parse is shutting down.

Was wondering how this will affect this library. It looks like they are open sourcing thier server. As someone new to programming and only knows swift, would like to know what we need to do to continue using this library in our project.

Thanks

**Comment by felix-dumit** [comment]
I heard the news but haven't looked too much into the limitations of the self hosted Parse server yet. 
But from what I understand the client side code would remain the same, so the only change here would be when installing, to move the cloud code to the corresponding self hosted alternative.

**Comment by otymartin** [comment]
Thanks felix that sounds like good news.
Hope you will continue supporting this library during this painful transition for many many developers.
Cheers!

**Comment by benitech** [comment]
@felix-dumit Hi Felix, Would it be possible for you to add your Digits Auth to the Parse-Server oAuth implementation so users could simply plug it in as another oAuth provider. 

(https://github.com/ParsePlatform/parse-server/tree/master/src/authDataManager)

You have all the stuff done here, so it should be a minor effort.

**Comment by felix-dumit** [comment]
Just to update this. I pushed a new version that doesn't require any additional cloudcode and works well with `parse-server`

**Comment by otymartin** [comment]
@felix-dumit 
No swift version?

**Comment by felix-dumit** [comment]
@otymartin I didn't bother translating it this time, it's better to just have one piece of code to maintain. You can still use this from swift though.

**Comment by otymartin** [comment]
@felix-dumit Cool just asking.
Thanks
