### ISSUE TITLE
Ambiguous use of 'Subscript' error in Xcode Beta 7.3

### ISSUE THREAD

**Issue by otymartin** [felix-dumit/PFUser-Digits#19]
<img width="549" alt="screen shot 2016-02-22 at 9 10 03 pm" src="https://cloud.githubusercontent.com/assets/2222881/13239495/c3e16310-d9a8-11e5-8d2e-85cde149fe86.png">

**Comment by felix-dumit** [comment]
I don't have xcode 7.3 installed but try on line 83 putting:
`guard let result = task.result as? [String:AnyObject]`

**Comment by otymartin** [comment]
Hey Felix,

It appears to have worked. Should I expect any behavioural changes in my app at all? Or should it work as before?
<img width="1280" alt="screen shot 2016-02-22 at 11 29 54 pm" src="https://cloud.githubusercontent.com/assets/2222881/13241778/491a141a-d9bc-11e5-98e4-a336837d9983.png">

**Comment by felix-dumit** [comment]
@otymartin No, this doesn't change any behaviour, just makes the type of `result` more explicit so the compiler doesn't complain.

**Comment by otymartin** [comment]
@felix-dumit Thanks :+1:
