### ISSUE TITLE
Link with already-existing parse user logged in using digits

### ISSUE THREAD

**Issue by mlchild** [felix-dumit/PFUser-Digits#2]
Hi, this tool looks great—is there any way to login with digits (creating an anonymous parse user) and then log back in with that digits phone number (in the event of, say, app deletion) and re-link with the same anonymous parse user? 

If this already exists, sorry for the bother, I just can't really tell based on the code.

**Comment by felix-dumit** [comment]
Hi,

As of my previous commit what you described is possible since I now support loggin in and linking with a digits account. So you can create an anonymous account but when you link it with digits it effectively becomes a digits account, so you later on can log back into it.
You can't however try to link another anonymous account to the same digits Id, this behaviour is the same if you try do it with Facebook.

I will update the readme to show the link with digits example

Hope it helps,

**Comment by mlchild** [comment]
Great, thanks!

**Comment by mlchild** [comment]
Quick question: with the new parse revocable sessions, it seems to change the session token every time you "set" the password. So if I login to the same digits account on a different phone or iPad, the person who is logged-in on a different device gets their token revoked. Is there any way around this problem?

Thanks again for this great framework.

**Comment by felix-dumit** [comment]
So here was the issue when the new Parse Revocable sessions were announced:
Previously each user had its own unique session token and we could fetch that in CloudCode and return to the user so he could log into that token.

With the revocable sessions, every login creates a new `Parse.Session` (with its own session token). I remember trying but I didn't find any way to get a new session token from CloudCode, the only solution to getting it was doing a login. But I couldn't do a login without the password, this is why the password is changed before every new login.

This is not the most ideal solution, I should look into and see if in any of the newest Parse updates they have included something that would make this easier.

However I did test this current implementation by logging into two different devices and the previous session was not revoked. If I go to the Parse dashboard I can see two sessions for that same user.

**Comment by mlchild** [comment]
Interesting—I've tried logging into two different devices and the previous session was revoked. Maybe it's something in our settings. Thanks for looking into it!

**Comment by felix-dumit** [comment]
When you say revoked, does the session object disappear from the Parse dashboard?

**Comment by mlchild** [comment]
It doesn't disappear but in the app I get "invalid session token" errors on all my fetches.

**Comment by felix-dumit** [comment]
If you are logged in with a user. Then you update that user's password in the dashboard does that result in the same errors?

**Comment by mlchild** [comment]
Yeah

**Comment by felix-dumit** [comment]
I tested on my app and it doesn't happen. Weird...
These is how my settings are:

<img width="1113" alt="screen shot 2015-10-16 at 4 34 30 pm" src="https://cloud.githubusercontent.com/assets/1863251/10555423/e1a1333e-7423-11e5-9825-cfcb44205ef1.png">

**Comment by felix-dumit** [comment]
It's probably this! 

In `General`. 

<img width="1125" alt="screen shot 2015-10-16 at 4 36 18 pm" src="https://cloud.githubusercontent.com/assets/1863251/10555432/1c652fa2-7424-11e5-9c71-71b6cbba5e2b.png">

**Comment by mlchild** [comment]
Awesome find! I will test but should be the fix! Thanks again.
