### ISSUE TITLE
Failure to Login because `Data couldn't be read`

### ISSUE THREAD

**Issue by otymartin** [felix-dumit/PFUser-Digits#20]
I've moved my Parse app to Google App Engine using MongoLab as my database.

I didn't bother migrating any data so its a clean slate.

My digits login/signup fails when attempting to login. I'm not entirely sure if this is a digits problem or something else but I'm posting it anyway.
<img width="914" alt="screen shot 2016-02-28 at 4 56 26 pm" src="https://cloud.githubusercontent.com/assets/2222881/13382188/3ffe2e8c-de3c-11e5-8b91-4d9a605578dd.png">
<img width="923" alt="screen shot 2016-02-28 at 4 56 32 pm" src="https://cloud.githubusercontent.com/assets/2222881/13382190/44746ea4-de3c-11e5-8aed-14c59e3a3118.png">

**Comment by felix-dumit** [comment]
I'm not sure if this is it, but you could try editing the cloud code files so that in `linkWithDigits` and `loginWithDigits`  it returns a JSON object e.g: `response.success({"result": true})`
You'd have to update the places in the iOS code that get the result from cloud code to react accordingly as well.

**Comment by otymartin** [comment]
@felix-dumit 
Unfortunately I don't know javascript enough to perform any edits and i'm unsure how to carry out edits on the iOS code. Would appreciate some guidance.

Unfortunately, I'm not experienced enough in programming to follow.
<img width="768" alt="screen shot 2016-02-28 at 10 33 47 pm" src="https://cloud.githubusercontent.com/assets/2222881/13385137/68189db0-de6b-11e5-86c6-090beb35ea11.png">
<img width="786" alt="screen shot 2016-02-28 at 10 33 55 pm" src="https://cloud.githubusercontent.com/assets/2222881/13385142/76dae290-de6b-11e5-9cb5-e81cd3665d41.png">

**Comment by felix-dumit** [comment]
Just wrap whatever is inside response.sucess inside a dictionary. 
response.sucess(X) -> response.success({"result": X})

**Comment by felix-dumit** [comment]
On ios you just need to adjust the parameter inside the PFUser.become call because cloudcode is now returning that value inside the dictionary so you need to get it (task.result["result"])

**Comment by otymartin** [comment]
@felix-dumit 
I get an unresolved identifier error
<img width="1002" alt="screen shot 2016-02-29 at 1 08 07 pm" src="https://cloud.githubusercontent.com/assets/2222881/13403973/8fcb027e-dee5-11e5-9948-4c45df4410f0.png">
Previously it was `PFUser.becomeInBackground($0.result as! String)`

**Comment by felix-dumit** [comment]
@otymartin Right, so just change it to `$0.result["result"]` or name the closure paramenter `{ task in ...`

Note that if the compiler complains about the subscript `["result"]`, you're going to have to do the same as what you did in #19
