### ISSUE TITLE
Invalid configuration

### ISSUE THREAD

**Issue by nilnilnull** [felix-dumit/PFUser-Digits#21]
Hi, thanks for the amazing tool.

I am getting this issue when calling `loginWithDigitsInBackground`:
`[TwitterKit] initWithAPIClient:configuration: Invalid parameter not satisfying: configuration`

I'm sure it is a mistake on my part though. Any help to point out where the issue could be? It's weird because I am supposed to see the DigitsKit and not Twitter since the change Twitter made a while ago (also mentioned in another issue).

Thanks in advance!

**Comment by felix-dumit** [comment]
Can you verify you are running the latest version of this library and also Digits?
I ask because previously their api did not accept the "configuration" parameter.

**Comment by nilnilnull** [comment]
The issue was not having the latest version of Digits. Thank you very much!

**Comment by nilnilnull** [comment]
Updated Digits, worked for first run but it logged in to another user's session. Reset content and settings of simulator, tried again and got the same issue. Running latest v of Digits and PFUser-Digits.

**Comment by felix-dumit** [comment]
When it logs in with digits it looks in parse for previous users with the same digits id, there probably is another user in your parse database with that id

**Comment by nilnilnull** [comment]
You are absolutely right. That was for the time it did actually run but now i keep getting the initial issue:
`[TwitterKit] initWithAPIClient:configuration: Invalid parameter not satisfying: configuration`

Any ideas?

**Comment by felix-dumit** [comment]
I would guess digits is not setup properly:
https://docs.fabric.io/ios/digits/digitskit-setup.html

**Comment by clsource** [comment]
I Solved this issue with this code

```
DGTAuthenticationConfiguration * configuration = [[DGTAuthenticationConfiguration alloc]
                                                      initWithAccountFields:DGTAccountFieldsEmail];

[[PFUser loginWithDigitsInBackgroundWithConfiguration:configuration] ....
```

Passing a nil object causes weird behavior.
may be should add a default config before calling the Digits shared instance.

```
#pragma mark - private Digits login
+ (BFTask *)_privateDigitsLoginWithConfiguration:(DGTAuthenticationConfiguration *)configuration
{
    BFTaskCompletionSource *taskCompletion = [BFTaskCompletionSource taskCompletionSource];

    if (!configuration) {
        configuration = [[DGTAuthenticationConfiguration alloc]
                         initWithAccountFields:DGTAccountFieldsEmail];

    }
```

cheers 👍

**Comment by felix-dumit** [comment]
@clsource Thanks, I added that for the objc version, it that was actually already in the swift version.
