### ISSUE TITLE
Invalid session token after linking an existing PFUser with Digits

### ISSUE THREAD

**Issue by cyrilchandelier** [felix-dumit/PFUser-Digits#22]
After linking an existing account with Digits using linkWithDigitsInBackground, I keep receiving these errors:

```
Error Domain=Parse Code=209 "invalid session token" UserInfo={code=209, temporary=0, error=invalid session token, NSLocalizedDescription=invalid session token}
```

Is there something specific to do to avoid these errors?

Thanks,
Cyril

**Comment by felix-dumit** [comment]
Check this: https://github.com/felix-dumit/PFUser-Digits#improvements
Might explain the issue you are having.

**Comment by cyrilchandelier** [comment]
I will try that, thanks; will keep you updated.
