### ISSUE TITLE
Revoke session on password change + Parse Server

### ISSUE THREAD

**Issue by hipwelljo** [felix-dumit/PFUser-Digits#23]
In the ReadMe, you mention we need to disable revoking sessions when user changes password if using revokable sessions. With Parse Server, revocable sessions is required, and so is revoking sessions when the password changes.

What impact does this have? How can we work around this issue, to ensure Digits + Parse login will continue to work when the session is revoked when the password changes?

**Comment by felix-dumit** [comment]
I'm working on a new version that will work with parse server and parse.com that doesn't have this issue. It won't require any additional cloudcode as well.

Best,

Felix

**Comment by hipwelljo** [comment]
Awesome! That's great to hear. Thank you Felix.
Do you have an expected completion date? I'm a bit pressed for time on this project.

**Comment by felix-dumit** [comment]
@hipwelljo Just pushed it now. I didn't do any testing outside of the current project I'm working on so let me know if it's working for you.

**Comment by hipwelljo** [comment]
Fantastic! I will try it today/tonight. Much much appreciated!
