### ISSUE TITLE
Parse Error Code 1 upon  loginWithDigitsInBackgroundWithConfiguration

### ISSUE THREAD

**Issue by hipwelljo** [felix-dumit/PFUser-Digits#24]
Using Parse Server, I've been able to log into Digits successfully, but then when it tries to log in with Parse (`loginWithDigitsInBackgroundWithConfiguration`) it fails. It looks like it's failing in `logInCurrentUserAsyncWithAuthType:authData:revocableSession:` as it's not triggering `continueWithSuccessBlock`. It does have auth data. I can successfully create a regular Parse user account.

`currentUser` is `nil` and `error` is:
`Error Domain=Parse Code=1 "{"code":1,"message":"Internal server error."}" UserInfo={error={"code":1,"message":"Internal server error."}, NSLocalizedDescription={"code":1,"message":"Internal server error."}, code=1}`

Let me know if you need any further information! Thanks

**Comment by felix-dumit** [comment]
@hipwelljo Can you access the server logs to see what was the error there?

**Comment by felix-dumit** [comment]
@hipwelljo Oh actually I think I know.. Did you configure the twitter oauth when you start the server?

E.g.

``` js
var api = new ParseServer({
    ...
    oauth: {
        twitter: {
            consumer_key: "BLA",
            consumer_secret: "BLA"
        },
        facebook: {
            appIds: "FACEBOOK"
        }
    }
});
```

I'll add that to the readme as well

**Comment by hipwelljo** [comment]
I think you nailed it. `TypeError: Cannot read property 'consumer_key' of undefined`. I don't have the code where that's configured but can get it. Can you point me to the location where I can find our consumer key and secret for twitter?

**Comment by felix-dumit** [comment]
@hipwelljo Open fabric website then go to the Digits page.
Url should be `https://fabric.io/{organization}/ios/apps/{bundle_id}/digits`

**Comment by hipwelljo** [comment]
Awesome thank you! I'll get that in there tomorrow and give it another go.

**Comment by hipwelljo** [comment]
I have been able to successfully log in, creating a new PFUser. We won't be supporting linking to an existing account so I can't test that flow. I'll let you know if I see any issues along the way, but so far so great. Thanks again! 💯
