### ISSUE TITLE
How to configure the Twitter/Digits oAuth on Parse Server

### ISSUE THREAD

**Issue by sidan5** [felix-dumit/PFUser-Digits#25]
I have only the config.json file and I'm not sure file syntax:

```
{
  "appId": "MY_APP_ID",
  "masterKey": "APP_MASTER_KEY",
  "appName": "APP NAME",
  "cloud": "./cloud/main",
  "databaseURI": "MONGODB_URI"

}
```

**Comment by felix-dumit** [comment]
I'm not sure if it works but you could try putting the "oauth" key and parameters inside the config.json

**Comment by sidan5** [comment]
Didn't worked. Have idea what's the exact syntax?

How do you configure Parse-Server?

**Comment by felix-dumit** [comment]
Why don't you have access to the code where the Parse server is created? 
Either way you should probably ask this in the parse-server repository as it's not specific to this library.

**Comment by sidan5** [comment]
I'm using the instructions to deploy local parse server you linked to... :/

**Comment by felix-dumit** [comment]
Oh I think I still have the old link to the parse website. Are you using the hosted Parse.com version then?

**Comment by sidan5** [comment]
Nope, Using local Parse Server...

**Comment by felix-dumit** [comment]
Here's the parse server sample application: https://github.com/ParsePlatform/parse-server-example

I suggest you fork that and start working on your server that way.
In the `index.js` file you can configure the oauth parameters.

**Comment by sidan5** [comment]
Issue was your library doesn't work on simulator. I believe would be a good practice to mention that...

**Comment by felix-dumit** [comment]
@sidan5 It works fine on the simulator, that's how I usually test it. Must've been something else you changed (it seemed you didn't have the oauth setup at all in the first place)
