### ISSUE TITLE
[Digits sharedInstance].session is sometimes nil causing crash

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [felix-dumit/PFUser-Digits#28]
In restoreAuthenticationWithAuthData, sometimes the session will be nil. At least in testing on the simulator. It appears to be random, not sure why it's sometimes nil. When that happens the next line down will crash trying to pull out userID from nil. To fix, I just added the following:
if (!session) {
    return NO;
}

Cheers

**Comment by felix-dumit** [comment]
@jordanhbuiltbyhq Do you mean here: https://github.com/felix-dumit/PFUser-Digits/blob/master/PFUser%2BDigits.m#L160 ?

**Comment by jordanhbuiltbyhq** [comment]
Yep precisely there.

**Comment by felix-dumit** [comment]
Hm, it shouldn't crash on objc since you can pass messages to nil. Are you sure that's the issue?

**Comment by jordanhbuiltbyhq** [comment]
I'm quite positive that was the cause. It shouldn't be because I'm using Swift and a bridging header to integrate with it right. I'll comment my fix out and let you know when I encounter it again.

**Comment by jordanhbuiltbyhq** [comment]
Ok this happened again. The problem isn't that the session is nil (although it is), the problem is authData is NSNull. 
![screen shot 2016-10-13 at 10 37 46 am](https://cloud.githubusercontent.com/assets/15804476/19357980/253ea812-9131-11e6-953a-d2d38be221ea.png)

**Comment by felix-dumit** [comment]
Hmm ok Interesting. I'll update to check against `NSNull` aswell then.
Thanks for looking into it!

**Comment by felix-dumit** [comment]
Fixed it here: https://github.com/felix-dumit/PFUser-Digits/commit/e1962ee80cf2c8bb8fe8d526ef936c97043f369e

Will close the issue
