### ISSUE TITLE
Digits is shutting down...

### ISSUE THREAD

**Issue by hasso92** [felix-dumit/PFUser-Digits#31]
Digits will stop working after Sept 30th.. It says we Need to move it to Firebase.. Or An Alternative would be Facebook AccountKit.. it would be great if you had an idea on how to update those codes to use either both. Sorry for the disturbance! i wish you a pleasant day!

**Comment by felix-dumit** [comment]
Thanks for the issue.
I have not migrated yet on the app I use this in. But when I do I'll update this with the solution I end up using.

**Comment by hasso92** [comment]
Great! Thank you! I'll be looking forward :)

**Comment by felix-dumit** [comment]
I commited the changes I made to get my app working with firebase.  https://github.com/felix-dumit/PFUser-Digits/commit/7cd089702e6715b32daf0096861da03f80192db1

Make sure to go over https://github.com/felix-dumit/PFUser-Digits#digits---firebase-migration in the readme.

Let me know if you have any trouble migrating.
