### ISSUE TITLE
Migration guide for hosted Parse Server

### ISSUE THREAD

**Issue by PaulSvetlichny** [felix-dumit/PFUser-Digits#32]
Hi, Thanks for the migration guide! Can you give me a clue on how to perform step (2) from your guide with a hosted Parse Server (Parse On Buddy)? I don't think I have a possibility to modify the server or add anything to the root (don't have access to their console or ftp at all) and any actions are restricted to Parse-like web interface.
Thanks in advice!

**Comment by felix-dumit** [comment]
You're going to have to get in contact with them to see if they can do it for you, I don't think there's another way
