### ISSUE TITLE
Error response from Twitter: Could not authenticate you.

### ISSUE THREAD

**Issue by agordeev** [felix-dumit/PFUser-Digits#6]
Hi there! First of all, thank you very much for this category, I found it very helpful!
I have successfully integrated Digits with your category for one of my apps. However, when I performed exactly the same steps for another app, this doesn't seems worked. I'm getting an error from verifyDigitsLogin cloud code function. Here are the logs:

```
I2015-09-17T05:02:07.425Z]OAuth oauth_signature="tz0J6GcxKKMDSma9%2cF9cKSiiGKg%3D",oauth_nonce="A603B1D1-2458-4999-80AA-E4CDF82B89C0",oauth_timestamp="1442463126",oauth_consumer_key="xIn9jwGoZDl7e2AzIUgMXN2ZI",oauth_token="3675347803-znGyo526xSQXt8W50d9am47tfNcFHG83OyQ10wT",oauth_version="1.0",oauth_signature_method="HMAC-SHA1"

I2015-09-17T05:02:07.576Z]{"uuid":"e8d06d7a-d53a-f820-e2ad-463ac93349d5","status":401,"headers":{"content-encoding":"gzip","content-length":"89","content-type":"application/json;charset=utf-8","date":"Thu, 17 Sep 2015 05:02:07 GMT","server":"tsa_b","strict-transport-security":"max-age=631138519","x-connection-hash":"358148c835d378f8571e04bb587dd80a","x-response-time":"17"},"text":"{\"errors\":[{\"code\":32,\"message\":\"Could not authenticate you.\"}]}","data":{"errors":[]},"buffer":[123,34,101,114,114,111,114,115,34,58,91,123,34,99,111,100,101,34,58,51,50,44,34,109,101,115,115,97,103,101,34,58,34,67,111,117,108,100,32,110,111,116,32,97,117,116,104,101,110,116,105,99,97,116,101,32,121,111,117,46,34,125,93,125],"cookies":{}}
```

Any ideas what's going on?

**Comment by felix-dumit** [comment]
Hey, I don't know for sure what it can be. Can you verify that in both of your apps the cloudcode and the category files are exactly the same? Maybe that is due to some update midway?

**Comment by agordeev** [comment]
Yes, they're exactly the same. I found that the issue disappears and reappears again.

**Comment by felix-dumit** [comment]
@andrew8712  Just curious if you ever found out what was happening here

**Comment by eneko** [comment]
@andrew8712 how did you setup Digits on your app? I recommend installing it via Fabric and making sure your keys are unique to that application.
