### ISSUE TITLE
how do I logout - parse error code 209

### ISSUE THREAD

**Issue by coderbec** [felix-dumit/PFUser-Digits#8]
Hey, 

So I'm pretty sure I'm doing it wrong, but after logging out with PFUser.logout(), so I'm getting " Failed to run command eventually with error: Error Domain=Parse Code=209 "invalid session token" UserInfo={code=209, temporary=0, error=invalid session token, NSLocalizedDescription=invalid session token}
"... 

Presumably I need to flush the session somehow.

Btw thanks so much for this repo. Digits is by far the better option tot he Twilio solution provided in parse docs.

**Comment by felix-dumit** [comment]
Hey,
- Can you verify that previous to logout out any other calls you made to Parse APIs did _NOT_ get this same error?
- Is this error printed during the logout call or due to some other call to Parse?
